{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Python-dotenv could not parse statement starting at line 1\n",
      "Python-dotenv could not parse statement starting at line 7\n"
     ]
    }
   ],
   "source": [
    "# Import necessary libraries\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from datasets import Dataset\n",
    "from ragas.metrics import AnswerSimilarity, AnswerCorrectness\n",
    "from ragas.evaluation import evaluate\n",
    "import os\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "load_dotenv()\n",
    "os.environ['OPENAI_API_KEY'] = os.getenv(\"OPENAI_API_KEY\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load the CSV file\n",
    "csv_file_path = '../Basline LLM evaluation/Eval_ChatGPT35.csv'\n",
    "\n",
    "try:\n",
    "    data = pd.read_csv(csv_file_path, encoding='utf-8')\n",
    "except UnicodeDecodeError:\n",
    "    data = pd.read_csv(csv_file_path, encoding='latin1')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "b51503c74eeb45519378f75e08ac99a9",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "7227a5e5bdee4541ade15fa107373ac5",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "4cd87a9cdd7d4769a1b6a0fe61b01ddd",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "53d0dff7e2fd4907bd0011bfdfb47c22",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "926cbec9e9ab4d5b82b7acd5bacbba5d",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "73ea6c0f929b4bd18abd25c62679fe7e",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-110' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-111' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-112' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-113' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "dc771e562209470eb67ea4b28802327a",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "6485c10d66564b7fab080125c592719c",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "e2d96bfbdce24e6fa6ca1e746f02432c",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-166' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-167' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-168' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-169' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "d9e925e74caa4eba95188fbc2cb496ba",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "00f8efbc37e34464862616d9494d5d37",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "5ee51f75e0234406b8125676e81a456a",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-223' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-224' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "98ef2154319d44dc83d84da59a844e80",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "c6ed6b542f4046d694bf09a2672bff74",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "f36cec8877a04f2ab248b8c97c96edb5",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-280' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-281' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "7cb0183ad50646928817845f9e14fc99",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "cec4991025d04556afe6934a073591e9",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "0e114a3872fe44edaf52ca25a6400e7e",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-338' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-339' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-340' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-341' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "7358c7d6b61a4e97a04e6dda0d66a838",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "d848dd82f88140859490b3b44c1bfa81",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "5881dd50ea0241b9876ca46431089919",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-396' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-397' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-398' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-399' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "6dfb3ad996b0464987d480ab1275425b",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "a823fdd2af8a46ceaa27bb30fd954d26",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "3deb4ecc7e834d4d8cc95ad9f6a3c4af",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-454' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-455' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "68d2d5a0c8af42619148c77011a459a6",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "d8fe8e9ed6e94797841d1f85a476d2d1",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "fc4815c91f7140ebb991445d19e88f51",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-512' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-513' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "681bd6df3709409c97fb3ecbeb9f974d",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "33da54ef0e3b4fcbb5d61f9277b98da7",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "7e2e4aa684844f5a850c5cea7ff5916c",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-569' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-570' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-571' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-572' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "9764bb178875484db73021fd7d553de1",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "1404e619d51344c9b8de4185934e4797",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "6aaa56a22ce0461a8c0ed1b5d4747388",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-626' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-627' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "b639683172304e9e8229b0d2d630c723",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "c3c590399e9148c095982d998c4b1a81",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "013376d2358345ad9a8b0005bba0570c",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-685' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-686' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "6088171844184feb9e59bb2964338d45",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "2161f735b36d4084983f9b73c08750d7",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "0b8ad5d49d414155a81e0f6861eabd35",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-743' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-744' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-745' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-746' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "ba926eac01df41c793bc76f4f0ac4d34",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "1dadb4354b264a23a9db1d97ebfdc3dc",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "e2e35bff17424785b90546daa7e717e4",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-801' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-802' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-803' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-804' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "f0f06da4d3634ba5b784ccac90debd54",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "69011d94736b4eb5b2bb756986d60f1b",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "bcc82f191bd341cea1fee409e818985c",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "d3797ff918354bae8af6ac689631a8ab",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "ea1c475c321a49efb6719d97efd63d54",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "455088b27e1648d9adf85fcc2ab2e428",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-912' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-913' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-914' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-915' coro=<AsyncClient.aclose() done, defined at C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpx\\_transports\\default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"C:\\Users\\York Yong\\AppData\\Roaming\\Python\\Python310\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\streams\\tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1181, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\proactor_events.py\", line 109, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\asyncio\\base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "2890f840404f42a3a3a1b4627f6d6531",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "ffc673a3c7ad49ebacf599ac97e19bae",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Define the metrics to be evaluated\n",
    "metrics = [\n",
    "    AnswerSimilarity(), \n",
    "    AnswerCorrectness()\n",
    "]\n",
    "\n",
    "# Initialize columns for results\n",
    "data['answer_similarity'] = None\n",
    "data['answer_correctness'] = None\n",
    "\n",
    "# Iterate over each row to evaluate the metrics individually\n",
    "for idx, row in data.iterrows():\n",
    "    evaluation_data = Dataset.from_dict({\n",
    "        'question': [row['question']],\n",
    "        'ground_truth': [row['ground_truth']],\n",
    "        'answer': [row['answer']]\n",
    "    })\n",
    "    \n",
    "    evaluation_result = evaluate(evaluation_data, metrics=metrics)\n",
    "    \n",
    "    # Store results back in the DataFrame\n",
    "    data.at[idx, 'answer_similarity'] = evaluation_result['answer_similarity']\n",
    "    data.at[idx, 'answer_correctness'] = evaluation_result['answer_correctness']\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>question</th>\n",
       "      <th>ground_truth</th>\n",
       "      <th>answer</th>\n",
       "      <th>answer_similarity</th>\n",
       "      <th>answer_correctness</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>What are the starting choices for Pokémon in P...</td>\n",
       "      <td>The starter Pokémon options in Paldea are Spri...</td>\n",
       "      <td>The starting choices for Pokémon in Paldea typ...</td>\n",
       "      <td>0.925629</td>\n",
       "      <td>0.681407</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>What special mounts are available in Pokémon S...</td>\n",
       "      <td>Scarlet players can catch and ride Koraidon, w...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" potential spe...</td>\n",
       "      <td>0.845774</td>\n",
       "      <td>0.211431</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>How does fast travel work in the game?</td>\n",
       "      <td>Fast travel is unlocked immediately and can be...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" fast travel l...</td>\n",
       "      <td>0.885288</td>\n",
       "      <td>0.649852</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>How do you initiate battles with other trainers?</td>\n",
       "      <td>Unlike past games, you must talk to trainers t...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" battles with ...</td>\n",
       "      <td>0.910511</td>\n",
       "      <td>0.227633</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>What can you collect from gimmighoul chests?</td>\n",
       "      <td>You can collect coins from gimmighoul chests.</td>\n",
       "      <td>In Pokémon Scarlet and Violet, Gimmighoul Ches...</td>\n",
       "      <td>0.86041</td>\n",
       "      <td>0.215118</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>How are items indicated in the game world?</td>\n",
       "      <td>Items are indicated by pokeballs or shiny spot...</td>\n",
       "      <td>In the game world of \"Pokémon Scarlet and Viol...</td>\n",
       "      <td>0.902749</td>\n",
       "      <td>0.725687</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>What benefits do sandwiches offer in the game?</td>\n",
       "      <td>Sandwiches provide buffs for 30 minutes durati...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" sandwiches li...</td>\n",
       "      <td>0.863989</td>\n",
       "      <td>0.215997</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>How can you prevent getting lost using the map?</td>\n",
       "      <td>Press the right analog stick to fix the map or...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" you can preve...</td>\n",
       "      <td>0.787715</td>\n",
       "      <td>0.196929</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>What is a recommended tactic for leveling up q...</td>\n",
       "      <td>Eating a Ham Sandwich (#80) to increase normal...</td>\n",
       "      <td>A recommended tactic for leveling up quickly i...</td>\n",
       "      <td>0.790238</td>\n",
       "      <td>0.197532</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>What are the three main storylines in Pokémon ...</td>\n",
       "      <td>The Gym Challenge, Starfall Street, and the Pa...</td>\n",
       "      <td>The three main storylines in \"Pokémon Scarlet ...</td>\n",
       "      <td>0.82194</td>\n",
       "      <td>0.205485</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>What abilities do defeating Titan Pokémon unlock?</td>\n",
       "      <td>Defeating Titan Pokémon unlocks new abilities ...</td>\n",
       "      <td>Defeating Titan Pokémon in \"Pokémon Scarlet an...</td>\n",
       "      <td>0.895339</td>\n",
       "      <td>0.598835</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>What are the recommended levels for fighting t...</td>\n",
       "      <td>The recommended levels for fighting Klawf are ...</td>\n",
       "      <td>For fighting the first Titan Pokémon in \"Pokém...</td>\n",
       "      <td>0.846505</td>\n",
       "      <td>0.211626</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>How does the battle mechanic change with gym l...</td>\n",
       "      <td>The final Pokémon used by gym leaders will Ter...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" the battle me...</td>\n",
       "      <td>0.85361</td>\n",
       "      <td>0.328787</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>What is the challenge format for Starfall Stre...</td>\n",
       "      <td>You must defeat 30 Pokémon in autobattles befo...</td>\n",
       "      <td>In Starfall Street missions in \"Pokémon Scarle...</td>\n",
       "      <td>0.807919</td>\n",
       "      <td>0.20198</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>How do you capture a second Koraidon or Miraid...</td>\n",
       "      <td>After completing the main story, a second Kora...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" you can captu...</td>\n",
       "      <td>0.879326</td>\n",
       "      <td>0.719832</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>How do you breed Pokémon in Scarlet and Violet?</td>\n",
       "      <td>Breeding involves having a Ditto and another P...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" you can breed...</td>\n",
       "      <td>0.863882</td>\n",
       "      <td>0.21597</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>What is the significance of the \"Area Zero\" mi...</td>\n",
       "      <td>It's a deep exploration mission involving the ...</td>\n",
       "      <td>The \"Area Zero\" mission in \"Pokémon Scarlet an...</td>\n",
       "      <td>0.833466</td>\n",
       "      <td>0.422652</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>What is required to evolve Pokémon like Eevee ...</td>\n",
       "      <td>Eevee requires specific stones or conditions l...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" evolving Eeve...</td>\n",
       "      <td>0.880497</td>\n",
       "      <td>0.553458</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>How can you earn more LP in the game?</td>\n",
       "      <td>LP can be earned through Tera Raid Battles and...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" you can earn ...</td>\n",
       "      <td>0.855191</td>\n",
       "      <td>0.213798</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>What type of team is recommended for the Elite...</td>\n",
       "      <td>A diverse team covering multiple types such as...</td>\n",
       "      <td>A balanced team that covers a wide range of ty...</td>\n",
       "      <td>0.860574</td>\n",
       "      <td>0.604032</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>How do Tera Raid Battles differ from regular b...</td>\n",
       "      <td>They allow multiple players to fight a single,...</td>\n",
       "      <td>Tera Raid Battles in \"Pokémon Scarlet and Viol...</td>\n",
       "      <td>0.837086</td>\n",
       "      <td>0.786195</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>What is the role of gimmighoul coins?</td>\n",
       "      <td>They are used to evolve Gimmighoul into Gholde...</td>\n",
       "      <td>Gimmighoul Coins in \"Pokémon Scarlet and Viole...</td>\n",
       "      <td>0.863313</td>\n",
       "      <td>0.215828</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>How do you obtain special items like the Chipp...</td>\n",
       "      <td>These can be found on the ground, bought at au...</td>\n",
       "      <td>Special items like the Chipped Pot or Auspicio...</td>\n",
       "      <td>0.819258</td>\n",
       "      <td>0.204814</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>What is the method to ensure a successful catc...</td>\n",
       "      <td>Turn off auto-save, use a Master Ball or set u...</td>\n",
       "      <td>To ensure a successful catch of legendary Poké...</td>\n",
       "      <td>0.833107</td>\n",
       "      <td>0.439046</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>What pokemon does Montenevera Chost Gym leader...</td>\n",
       "      <td>Rymn, the gym leader for Montenevera Ghost Gym...</td>\n",
       "      <td>The Montenevera Ghost-type Gym Leader in \"Poké...</td>\n",
       "      <td>0.887094</td>\n",
       "      <td>0.221774</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>What is the recipe for Electric Shiny Sandwich?</td>\n",
       "      <td>You will need the following:\\nYellow Bell Pepp...</td>\n",
       "      <td>The recipe for an Electric Shiny Sandwich in \"...</td>\n",
       "      <td>0.75444</td>\n",
       "      <td>0.18861</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>Who is the Real Cassiopeia?</td>\n",
       "      <td>The Real Cassiopeia is Penny</td>\n",
       "      <td>The Real Cassiopeia in \"Pokémon Scarlet and Vi...</td>\n",
       "      <td>0.869616</td>\n",
       "      <td>0.217404</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>What are the weakness of the Titan Bombirdier?</td>\n",
       "      <td>Bombirdier is weak to Fairy, Rock and Electric.</td>\n",
       "      <td>The Titan Bombirdier in \"Pokémon Scarlet and V...</td>\n",
       "      <td>0.913592</td>\n",
       "      <td>0.728398</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>Where can I heal my pokemon in Area Zero?</td>\n",
       "      <td>You can use the bed in the research stations t...</td>\n",
       "      <td>In Area Zero in \"Pokémon Scarlet and Violet,\" ...</td>\n",
       "      <td>0.853811</td>\n",
       "      <td>0.213453</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>What moves do I need to battle against the Pro...</td>\n",
       "      <td>You will need good Fairy, Psychic, Ground and ...</td>\n",
       "      <td>To battle against Professor Turo in \"Pokémon S...</td>\n",
       "      <td>0.837087</td>\n",
       "      <td>0.481999</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>What is required to evolve Charcadet into Arma...</td>\n",
       "      <td>Auspicious Armor</td>\n",
       "      <td>To evolve Charcadet into Armarouge in \"Pokémon...</td>\n",
       "      <td>0.765826</td>\n",
       "      <td>0.19145</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>Which pokemon requires walking with Let's Go t...</td>\n",
       "      <td>Pawno with walking 1000 steps to Pawmot. Bramb...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" the Pokémon t...</td>\n",
       "      <td>0.767169</td>\n",
       "      <td>0.191792</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>In the Champion Assessment, what is the name o...</td>\n",
       "      <td>Tulip - Psychic Type Gym Leader located in Alf...</td>\n",
       "      <td>In the Champion Assessment, the name of the Gy...</td>\n",
       "      <td>0.787016</td>\n",
       "      <td>0.196754</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>How to defeat Elite Four Member Hassel?</td>\n",
       "      <td>Hassel is a Dragon specialist who is weak to I...</td>\n",
       "      <td>To defeat Elite Four Member Hassel in \"Pokémon...</td>\n",
       "      <td>0.87154</td>\n",
       "      <td>0.432171</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>Where is Pokemon League?</td>\n",
       "      <td>It is located in the back of Mesagoza, in the ...</td>\n",
       "      <td>The Pokémon League in \"Pokémon Scarlet and Vio...</td>\n",
       "      <td>0.817514</td>\n",
       "      <td>0.204378</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>How do you turn off the time machine in Area Z...</td>\n",
       "      <td>You have to place the book Arven gave you earl...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" turning off t...</td>\n",
       "      <td>0.822215</td>\n",
       "      <td>0.205554</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>Where can you find gimmighoul's chest?</td>\n",
       "      <td>You can go to the top of the Watchtowers.</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" Gimmighoul's ...</td>\n",
       "      <td>0.731914</td>\n",
       "      <td>0.182975</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>Where can I find soothe bells?</td>\n",
       "      <td>It is a hold item purchased at the Delibird st...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" you can typic...</td>\n",
       "      <td>0.779149</td>\n",
       "      <td>0.194787</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>I keep going in the wrong direction, how do I ...</td>\n",
       "      <td>When you open your map, you might notice it ca...</td>\n",
       "      <td>To fix consistently going in the wrong directi...</td>\n",
       "      <td>0.848425</td>\n",
       "      <td>0.407759</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>I've heard I can climb mountains, how do I do ...</td>\n",
       "      <td>Upon defeating the LAST titan you will be able...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" you can typic...</td>\n",
       "      <td>0.817586</td>\n",
       "      <td>0.204396</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>I can't get past gym 6, help!</td>\n",
       "      <td>Gym #6 - Montenevera Ghost Gym - Rymn. Weaknes...</td>\n",
       "      <td>To help you get past Gym 6 in \"Pokémon Scarlet...</td>\n",
       "      <td>0.836979</td>\n",
       "      <td>0.349864</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>How do I fight Dragon pokemon?</td>\n",
       "      <td>Dragon is weak to: Ice, Fairy and Dragon Types</td>\n",
       "      <td>To effectively fight Dragon-type Pokémon in \"P...</td>\n",
       "      <td>0.863971</td>\n",
       "      <td>0.562148</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>What is the final battle mission of the game?</td>\n",
       "      <td>After defeating the professor, thats not all!...</td>\n",
       "      <td>The final battle mission of the game in \"Pokém...</td>\n",
       "      <td>0.828569</td>\n",
       "      <td>0.207142</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>How do I get a Polteageist?</td>\n",
       "      <td>Pokemon who need other items to evolve: Sinist...</td>\n",
       "      <td>To obtain a Polteageist in \"Pokémon Scarlet an...</td>\n",
       "      <td>0.910259</td>\n",
       "      <td>0.870422</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>I'm trying to get a Marill, how do I do that?</td>\n",
       "      <td>Pokemon that require a high level of friendshi...</td>\n",
       "      <td>To obtain a Marill in \"Pokémon Scarlet and Vio...</td>\n",
       "      <td>0.819932</td>\n",
       "      <td>0.204983</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>List down all the gyms.</td>\n",
       "      <td>There are 8 gyms - Cortondo, Artazon, Levinici...</td>\n",
       "      <td>In \"Pokémon Scarlet and Violet,\" the gyms are ...</td>\n",
       "      <td>0.813347</td>\n",
       "      <td>0.203339</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>How does the \"Let's Go\" feature affect Pokémon...</td>\n",
       "      <td>Certain Pokémon evolve after walking a require...</td>\n",
       "      <td>The \"Let's Go\" feature in \"Pokémon Scarlet and...</td>\n",
       "      <td>0.861103</td>\n",
       "      <td>0.402776</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>What happens after I defeat the Elite Four?</td>\n",
       "      <td>After youve defeated Geeta, youre the newest...</td>\n",
       "      <td>After defeating the Elite Four in \"Pokémon Sca...</td>\n",
       "      <td>0.846744</td>\n",
       "      <td>0.7474</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>What level are the Professor's Pokemon in Area...</td>\n",
       "      <td>Level 66 and Level 67</td>\n",
       "      <td>The Professor's Pokémon in Area Zero are typic...</td>\n",
       "      <td>0.810709</td>\n",
       "      <td>0.577677</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>How do I evolve a Sunflora?</td>\n",
       "      <td>Pokemon who require stones to evolve: Sunkern ...</td>\n",
       "      <td>To evolve a Sunflora into a Sunflora in \"Pokém...</td>\n",
       "      <td>0.915389</td>\n",
       "      <td>0.228846</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                             question  \\\n",
       "0   What are the starting choices for Pokémon in P...   \n",
       "1   What special mounts are available in Pokémon S...   \n",
       "2              How does fast travel work in the game?   \n",
       "3    How do you initiate battles with other trainers?   \n",
       "4        What can you collect from gimmighoul chests?   \n",
       "5          How are items indicated in the game world?   \n",
       "6      What benefits do sandwiches offer in the game?   \n",
       "7     How can you prevent getting lost using the map?   \n",
       "8   What is a recommended tactic for leveling up q...   \n",
       "9   What are the three main storylines in Pokémon ...   \n",
       "10  What abilities do defeating Titan Pokémon unlock?   \n",
       "11  What are the recommended levels for fighting t...   \n",
       "12  How does the battle mechanic change with gym l...   \n",
       "13  What is the challenge format for Starfall Stre...   \n",
       "14  How do you capture a second Koraidon or Miraid...   \n",
       "15    How do you breed Pokémon in Scarlet and Violet?   \n",
       "16  What is the significance of the \"Area Zero\" mi...   \n",
       "17  What is required to evolve Pokémon like Eevee ...   \n",
       "18              How can you earn more LP in the game?   \n",
       "19  What type of team is recommended for the Elite...   \n",
       "20  How do Tera Raid Battles differ from regular b...   \n",
       "21              What is the role of gimmighoul coins?   \n",
       "22  How do you obtain special items like the Chipp...   \n",
       "23  What is the method to ensure a successful catc...   \n",
       "24  What pokemon does Montenevera Chost Gym leader...   \n",
       "25    What is the recipe for Electric Shiny Sandwich?   \n",
       "26                        Who is the Real Cassiopeia?   \n",
       "27    What are the weakness of the Titan Bombirdier?    \n",
       "28          Where can I heal my pokemon in Area Zero?   \n",
       "29  What moves do I need to battle against the Pro...   \n",
       "30  What is required to evolve Charcadet into Arma...   \n",
       "31  Which pokemon requires walking with Let's Go t...   \n",
       "32  In the Champion Assessment, what is the name o...   \n",
       "33            How to defeat Elite Four Member Hassel?   \n",
       "34                           Where is Pokemon League?   \n",
       "35  How do you turn off the time machine in Area Z...   \n",
       "36             Where can you find gimmighoul's chest?   \n",
       "37                     Where can I find soothe bells?   \n",
       "38  I keep going in the wrong direction, how do I ...   \n",
       "39  I've heard I can climb mountains, how do I do ...   \n",
       "40                      I can't get past gym 6, help!   \n",
       "41                     How do I fight Dragon pokemon?   \n",
       "42      What is the final battle mission of the game?   \n",
       "43                        How do I get a Polteageist?   \n",
       "44      I'm trying to get a Marill, how do I do that?   \n",
       "45                            List down all the gyms.   \n",
       "46  How does the \"Let's Go\" feature affect Pokémon...   \n",
       "47        What happens after I defeat the Elite Four?   \n",
       "48  What level are the Professor's Pokemon in Area...   \n",
       "49                        How do I evolve a Sunflora?   \n",
       "\n",
       "                                         ground_truth  \\\n",
       "0   The starter Pokémon options in Paldea are Spri...   \n",
       "1   Scarlet players can catch and ride Koraidon, w...   \n",
       "2   Fast travel is unlocked immediately and can be...   \n",
       "3   Unlike past games, you must talk to trainers t...   \n",
       "4       You can collect coins from gimmighoul chests.   \n",
       "5   Items are indicated by pokeballs or shiny spot...   \n",
       "6   Sandwiches provide buffs for 30 minutes durati...   \n",
       "7   Press the right analog stick to fix the map or...   \n",
       "8   Eating a Ham Sandwich (#80) to increase normal...   \n",
       "9   The Gym Challenge, Starfall Street, and the Pa...   \n",
       "10  Defeating Titan Pokémon unlocks new abilities ...   \n",
       "11  The recommended levels for fighting Klawf are ...   \n",
       "12  The final Pokémon used by gym leaders will Ter...   \n",
       "13  You must defeat 30 Pokémon in autobattles befo...   \n",
       "14  After completing the main story, a second Kora...   \n",
       "15  Breeding involves having a Ditto and another P...   \n",
       "16  It's a deep exploration mission involving the ...   \n",
       "17  Eevee requires specific stones or conditions l...   \n",
       "18  LP can be earned through Tera Raid Battles and...   \n",
       "19  A diverse team covering multiple types such as...   \n",
       "20  They allow multiple players to fight a single,...   \n",
       "21  They are used to evolve Gimmighoul into Gholde...   \n",
       "22  These can be found on the ground, bought at au...   \n",
       "23  Turn off auto-save, use a Master Ball or set u...   \n",
       "24  Rymn, the gym leader for Montenevera Ghost Gym...   \n",
       "25  You will need the following:\\nYellow Bell Pepp...   \n",
       "26                       The Real Cassiopeia is Penny   \n",
       "27    Bombirdier is weak to Fairy, Rock and Electric.   \n",
       "28  You can use the bed in the research stations t...   \n",
       "29  You will need good Fairy, Psychic, Ground and ...   \n",
       "30                                   Auspicious Armor   \n",
       "31  Pawno with walking 1000 steps to Pawmot. Bramb...   \n",
       "32  Tulip - Psychic Type Gym Leader located in Alf...   \n",
       "33  Hassel is a Dragon specialist who is weak to I...   \n",
       "34  It is located in the back of Mesagoza, in the ...   \n",
       "35  You have to place the book Arven gave you earl...   \n",
       "36          You can go to the top of the Watchtowers.   \n",
       "37  It is a hold item purchased at the Delibird st...   \n",
       "38  When you open your map, you might notice it ca...   \n",
       "39  Upon defeating the LAST titan you will be able...   \n",
       "40  Gym #6 - Montenevera Ghost Gym - Rymn. Weaknes...   \n",
       "41     Dragon is weak to: Ice, Fairy and Dragon Types   \n",
       "42  After defeating the professor, thats not all!...   \n",
       "43  Pokemon who need other items to evolve: Sinist...   \n",
       "44  Pokemon that require a high level of friendshi...   \n",
       "45  There are 8 gyms - Cortondo, Artazon, Levinici...   \n",
       "46  Certain Pokémon evolve after walking a require...   \n",
       "47  After youve defeated Geeta, youre the newest...   \n",
       "48                              Level 66 and Level 67   \n",
       "49  Pokemon who require stones to evolve: Sunkern ...   \n",
       "\n",
       "                                               answer answer_similarity  \\\n",
       "0   The starting choices for Pokémon in Paldea typ...          0.925629   \n",
       "1   In \"Pokémon Scarlet and Violet,\" potential spe...          0.845774   \n",
       "2   In \"Pokémon Scarlet and Violet,\" fast travel l...          0.885288   \n",
       "3   In \"Pokémon Scarlet and Violet,\" battles with ...          0.910511   \n",
       "4   In Pokémon Scarlet and Violet, Gimmighoul Ches...           0.86041   \n",
       "5   In the game world of \"Pokémon Scarlet and Viol...          0.902749   \n",
       "6   In \"Pokémon Scarlet and Violet,\" sandwiches li...          0.863989   \n",
       "7   In \"Pokémon Scarlet and Violet,\" you can preve...          0.787715   \n",
       "8   A recommended tactic for leveling up quickly i...          0.790238   \n",
       "9   The three main storylines in \"Pokémon Scarlet ...           0.82194   \n",
       "10  Defeating Titan Pokémon in \"Pokémon Scarlet an...          0.895339   \n",
       "11  For fighting the first Titan Pokémon in \"Pokém...          0.846505   \n",
       "12  In \"Pokémon Scarlet and Violet,\" the battle me...           0.85361   \n",
       "13  In Starfall Street missions in \"Pokémon Scarle...          0.807919   \n",
       "14  In \"Pokémon Scarlet and Violet,\" you can captu...          0.879326   \n",
       "15  In \"Pokémon Scarlet and Violet,\" you can breed...          0.863882   \n",
       "16  The \"Area Zero\" mission in \"Pokémon Scarlet an...          0.833466   \n",
       "17  In \"Pokémon Scarlet and Violet,\" evolving Eeve...          0.880497   \n",
       "18  In \"Pokémon Scarlet and Violet,\" you can earn ...          0.855191   \n",
       "19  A balanced team that covers a wide range of ty...          0.860574   \n",
       "20  Tera Raid Battles in \"Pokémon Scarlet and Viol...          0.837086   \n",
       "21  Gimmighoul Coins in \"Pokémon Scarlet and Viole...          0.863313   \n",
       "22  Special items like the Chipped Pot or Auspicio...          0.819258   \n",
       "23  To ensure a successful catch of legendary Poké...          0.833107   \n",
       "24  The Montenevera Ghost-type Gym Leader in \"Poké...          0.887094   \n",
       "25  The recipe for an Electric Shiny Sandwich in \"...           0.75444   \n",
       "26  The Real Cassiopeia in \"Pokémon Scarlet and Vi...          0.869616   \n",
       "27  The Titan Bombirdier in \"Pokémon Scarlet and V...          0.913592   \n",
       "28  In Area Zero in \"Pokémon Scarlet and Violet,\" ...          0.853811   \n",
       "29  To battle against Professor Turo in \"Pokémon S...          0.837087   \n",
       "30  To evolve Charcadet into Armarouge in \"Pokémon...          0.765826   \n",
       "31  In \"Pokémon Scarlet and Violet,\" the Pokémon t...          0.767169   \n",
       "32  In the Champion Assessment, the name of the Gy...          0.787016   \n",
       "33  To defeat Elite Four Member Hassel in \"Pokémon...           0.87154   \n",
       "34  The Pokémon League in \"Pokémon Scarlet and Vio...          0.817514   \n",
       "35  In \"Pokémon Scarlet and Violet,\" turning off t...          0.822215   \n",
       "36  In \"Pokémon Scarlet and Violet,\" Gimmighoul's ...          0.731914   \n",
       "37  In \"Pokémon Scarlet and Violet,\" you can typic...          0.779149   \n",
       "38  To fix consistently going in the wrong directi...          0.848425   \n",
       "39  In \"Pokémon Scarlet and Violet,\" you can typic...          0.817586   \n",
       "40  To help you get past Gym 6 in \"Pokémon Scarlet...          0.836979   \n",
       "41  To effectively fight Dragon-type Pokémon in \"P...          0.863971   \n",
       "42  The final battle mission of the game in \"Pokém...          0.828569   \n",
       "43  To obtain a Polteageist in \"Pokémon Scarlet an...          0.910259   \n",
       "44  To obtain a Marill in \"Pokémon Scarlet and Vio...          0.819932   \n",
       "45  In \"Pokémon Scarlet and Violet,\" the gyms are ...          0.813347   \n",
       "46  The \"Let's Go\" feature in \"Pokémon Scarlet and...          0.861103   \n",
       "47  After defeating the Elite Four in \"Pokémon Sca...          0.846744   \n",
       "48  The Professor's Pokémon in Area Zero are typic...          0.810709   \n",
       "49  To evolve a Sunflora into a Sunflora in \"Pokém...          0.915389   \n",
       "\n",
       "   answer_correctness  \n",
       "0            0.681407  \n",
       "1            0.211431  \n",
       "2            0.649852  \n",
       "3            0.227633  \n",
       "4            0.215118  \n",
       "5            0.725687  \n",
       "6            0.215997  \n",
       "7            0.196929  \n",
       "8            0.197532  \n",
       "9            0.205485  \n",
       "10           0.598835  \n",
       "11           0.211626  \n",
       "12           0.328787  \n",
       "13            0.20198  \n",
       "14           0.719832  \n",
       "15            0.21597  \n",
       "16           0.422652  \n",
       "17           0.553458  \n",
       "18           0.213798  \n",
       "19           0.604032  \n",
       "20           0.786195  \n",
       "21           0.215828  \n",
       "22           0.204814  \n",
       "23           0.439046  \n",
       "24           0.221774  \n",
       "25            0.18861  \n",
       "26           0.217404  \n",
       "27           0.728398  \n",
       "28           0.213453  \n",
       "29           0.481999  \n",
       "30            0.19145  \n",
       "31           0.191792  \n",
       "32           0.196754  \n",
       "33           0.432171  \n",
       "34           0.204378  \n",
       "35           0.205554  \n",
       "36           0.182975  \n",
       "37           0.194787  \n",
       "38           0.407759  \n",
       "39           0.204396  \n",
       "40           0.349864  \n",
       "41           0.562148  \n",
       "42           0.207142  \n",
       "43           0.870422  \n",
       "44           0.204983  \n",
       "45           0.203339  \n",
       "46           0.402776  \n",
       "47             0.7474  \n",
       "48           0.577677  \n",
       "49           0.228846  "
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Display the evaluation results\n",
    "result_df = data[['question', 'ground_truth', 'answer', 'answer_similarity', 'answer_correctness']]\n",
    "result_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mean Answer Similarity: 0.8430862823001819\n",
      "Mean Answer Correctness: 0.3612435049663631\n"
     ]
    }
   ],
   "source": [
    "# Print the mean values of answer_similarity and answer_correctness\n",
    "print(\"Mean Answer Similarity:\", data['answer_similarity'].replace(np.nan, 0).mean())\n",
    "print(\"Mean Answer Correctness:\", data['answer_correctness'].replace(np.nan, 0).mean())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
